name: Say Hello

on:
  push:
    branches-ignore:
      - dev

jobs:
  sayhello:
    name: Hello, World!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Say Hello
        run: |
          echo "Hello, world!"